apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "backend-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ include "backend-app.serviceAccountName" . }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port | default 80 }}
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: {{ .Values.frontend.env.BACKEND_URL | quote }}
          {{- if .Values.frontend.resources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15 # Légèrement augmenté pour plus de sécurité
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10